package com.github.proteanbear.libra.framework;

import com.github.proteanbear.libra.utils.StringUtils;
import org.quartz.JobDataMap;

/**
 * Task configuration.
 *
 * @author ProteanBear
 */
public class TaskConfigBean
{
    /**
     * The main key.</br>
     * Generated by default using uuid.
     */
    private String taskId=StringUtils.uuid();

    /**
     * Class corresponding to the task key
     */
    private String taskKey;

    /**
     * The status of the task, 0 disabled or 1 enabled
     */
    private int taskStatus=1;

    /**
     * Task timing settings
     */
    private String taskCron;

    /**
     * Task data map
     */
    private final JobDataMap jobDataMap=new JobDataMap();

    public String getTaskId()
    {
        return taskId;
    }

    public void setTaskId(String taskId)
    {
        this.taskId=taskId;
    }

    public String getTaskKey()
    {
        return taskKey;
    }

    public void setTaskKey(String taskKey)
    {
        this.taskKey=taskKey;
    }

    public int getTaskStatus()
    {
        return taskStatus;
    }

    public void setTaskStatus(int taskStatus)
    {
        this.taskStatus=taskStatus;
    }

    public String getTaskCron()
    {
        return taskCron;
    }

    public void setTaskCron(String taskCron)
    {
        this.taskCron=taskCron;
    }

    public JobDataMap getJobDataMap()
    {
        return jobDataMap;
    }
}